language: zh-CN

# main menu navigation
menu:
  home: /
  archives: /archives
  tools: /tools
  production: /production
  about: /about


head:
    keywords: 
    description: 


# Miscelaneous
favicon: /favicon.ico

show_post_category: true
show_post_tags: true

active_nav: false # show active status on nav menu

sidebar: true # whether to show the sidebar
widgets:
  # - category
  # - tag
  # - tagcloud
  # - archive
  - recent_posts
  - links
links:
  - title: "GitHub"
    url: http://www.github.com/FangWW
    intro: "GITHUB"

# disqus_shortname: fangjw
# duoshuo_shortname: fangjw
#site statistic
#google_analytics:  
baidu_analytics: 4279176d249d3665968eabda2797410d
#baidu_analytics: 


